about controller/OnlineNoticeBoard/config/routes.rb
Rails.application.routes.draw do
  resources :tutorials
	get '/books/search' 
  resources :feedbacks
   resources :home
   root 'home#index'
   
   post 'home/new' => 'home#create'
   post 'home/:id/edit' => 'home#update'
    get 'home/:id/show' => 'home#show'
    get '/home/:id/destroy' => 'home#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

about controller/OnlineNoticeBoard/app/models/feedback.rb
class Feedback < ApplicationRecord
end

about controller/OnlineNoticeBoard/app/models/tiltecontent.rb
class Tiltecontent < ApplicationRecord
	#validates :title, :content, :presence => true
    #validates :title, :length => {:minimum => 2}
    #validates :title, :uniqueness => {:message => "already taken"}
    def self.search(search)
    	if search
    		where('title like ?',"%#{search}%")
    	else
    		all
    	end
    end
end

about controller/OnlineNoticeBoard/app/models/tutorial.rb
class Tutorial < ApplicationRecord
end

about controller/OnlineNoticeBoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
end

about controller/OnlineNoticeBoard/app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:name, :comment)
    end
end

about controller/OnlineNoticeBoard/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  #params[:page] ||=1
  debugger
    @titlecontents = Tiltecontent.search(params[:search]).order(:title).paginate(:per_page => 1,:page => params[:page])

  	#@titlecontents = Tiltecontent.all
    #render json: {new: "msg", data: @titlecontents}
  end

  def new
  	@titlecontent = Tiltecontent.new
  end

  def create
  	# debugger
  	@titlecontent = Tiltecontent.new(titlecontent_params)
  	if @titlecontent.save
  		redirect_to '/'
  	else
  		render 'new'
  	end
  end
  def delete

  end

  def destroy
  	@titlecontent = Tiltecontent.find(params[:id])
    @titlecontent.destroy
	redirect_to '/'
  end

  def show
    @titlecontent = Tiltecontent.find(params[:id])
    #render json: {new: "msg", data: @titlecontent}
  end

  def edit
  	@titlecontent = Tiltecontent.find(params[:id])
  end
  def update
  	@titlecontent = Tiltecontent.find(params[:id])
    @titlecontent.update(titlecontent_params)
	redirect_to '/'
  end
  

  def titlecontent_params
  	params.require(:tiltecontent).permit(:title, :content)
  end
end

about controller/OnlineNoticeBoard/app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
	def index
    @tutorials = Tutorial.all
  end

end

about controller/OnlineNoticeBoard/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

about controller/OnlineNoticeBoard/app/helpers/tutorials_helper.rb
module TutorialsHelper
end

about controller/OnlineNoticeBoard/app/views/home/edit.html.erb
<center><h1>Update Notice</h1></center>
<%= form_for Tiltecontent.new, url:""  do |form|%>


<h1>enter comment</h1>
<%= form.text_area :content, size: "30x10" %><br>




<%= form.submit "Update"%>
<% end %>

about controller/OnlineNoticeBoard/app/views/home/index.html.erb
<center><h1>Our Blogs</h1></center>
 
  <% if @titlecontents.empty? %>
    <b><p>There are no posts</p></b> 
  <%else%>
    <% @titlecontents.each do|titlecontent|%>
      <%= titlecontent.title %><br>
      <%= titlecontent.content%><br>
      <%= link_to 'edit' ,"home/#{titlecontent.id}/edit"%>
      <%= link_to 'delete' ,"home/#{titlecontent.id}/destroy"%><hr>
    <% end %>
  <% end %>   

 

<%= form_tag home_index_path, :method => 'get' do %>
  <p>
    <%= text_field_tag  %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="products"><%# render 'products' %></div>
<% end %>


  <%= will_paginate @titlecontents%>
  

about controller/OnlineNoticeBoard/app/views/home/new.html.erb
<center><h1>Create New Notice</h1></center>
  <% if @titlecontent.errors.any? %>
      <h2>Errors:</h2>
        <ul>
          <%= @titlecontent.errors.full_messages.each do |message|%>
            <li> 
            	<%= message %>
            </li>
          <% end %>
        </ul>
  <% end %>
  <%= form_for @titlecontent, url:"" do |form|%>
    <h1>enter title</h1>
      <%= form.text_field :title%><br>
    <h1>enter comment</h1>
      <%= form.text_area :content, size: "30x10" %><br>
      <%= form.submit "NoticeGenerate"%>
  <% end %>

about controller/OnlineNoticeBoard/app/views/home/show.html.erb
<%= link_to 'Delete this record',@titlecontent, method: :delete, data: {confirm: 'Are You Sure?'} %><br>

about controller/OnlineNoticeBoard/app/views/tutorials/index.html.erb
<h1>Tutorials</h1>

<ul>
  <% @tutorials.each do |tutorial| %>
    <li>
    	<%= tutorial.title %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => false} %>
    </li>
  <% end %>
</ul>