HrManagementSystem/config/routes.rb
Rails.application.routes.draw do
  devise_for :students
 resources :home
 root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HrManagementSystem/app/models/address.rb
class Address < ApplicationRecord
end

HrManagementSystem/app/models/department.rb
class Department < ApplicationRecord
	has_many :employees
end

HrManagementSystem/app/models/designation.rb
class Designation < ApplicationRecord
	has_many :employees, through: :employee_designations
	has_many :employee_designations
end

HrManagementSystem/app/models/employee.rb
class Employee < ApplicationRecord
	has_many :desginations, through: :employee_designations
	has_many :employee_designations
	belongs_to :role
	belongs_to :department
end

HrManagementSystem/app/models/employee_designation.rb
class EmployeeDesignation < ApplicationRecord
	belongs_to :employee
    belongs_to :designation
end

HrManagementSystem/app/models/role.rb
class Role < ApplicationRecord
	has_many :employees
end

HrManagementSystem/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	

  end

  def new
  end

  def edit
  end

  def show
  end
end

HrManagementSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
    <% if student_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_student_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_student_session_path)  %>  
  </li>
<% end %>
  </body>
</html>